/* this file is automatically generated by 'make'; do not edit! */
#ifndef DEFS_H
# define  RCSMAKEID "@(#)$Id: Makefile.in,v 1.41 2007-01-30 14:10:28 piefel Exp $"
# define  KIMWITUCOPYRIGHT "@(#)$Author: Kimwitu++ version 2.3.11 (C) 1998-2007 Humboldt-University of Berlin $"
# define  KC_USE_STAT
# define  KIMWITURELEASE "@(#)RELEASE VERSION 2.3.11"
# define  KIMWITUVERSIONSTRING "2.3.11"
# define  METAKIMWITUVERSIONMAJOR 2
# define  METAKIMWITUVERSIONMINOR 3
# define  METAKIMWITUVERSIONMICRO 11
#endif /* DEFS_H */
